// Generated by tools/generate-characters.cjs from DiceBear "Bottts" (https://www.dicebear.com/styles/bottts/),
// design by Pablo Stanley (https://bottts.com/), "free for personal and commercial use". Regenerate rather than edit.

import type { MiniMood } from '../../types'
import { BIP } from './bip'
import { BOLT } from './bolt'
import { VINTIK } from './vintik'
import { SHPUNTIK } from './shpuntik'
import { ISKRA } from './iskra'
import { LUNA } from './luna'
import { GAIKA } from './gaika'
import { PIXEL } from './pixel'
import { ROBI } from './robi'
import { KUBIK } from './kubik'
import { TESLA } from './tesla'
import { MAYAK } from './mayak'
import { SENSOR } from './sensor'
import { MOH } from './moh'
import { CHIP } from './chip'
import { RYZHIK } from './ryzhik'
import { LIMON } from './limon'
import { GRAFIT } from './grafit'
import { OLIVKA } from './olivka'
import { KOSMO } from './kosmo'

export type MiniCharacter = { id: string; name: { ru: string; en: string }; moods: Record<MiniMood, string> }

export const CHARACTERS: MiniCharacter[] = [
  { id: 'bip', name: { ru: 'Бип', en: 'Beep' }, moods: BIP },
  { id: 'bolt', name: { ru: 'Болт', en: 'Bolt' }, moods: BOLT },
  { id: 'vintik', name: { ru: 'Винтик', en: 'Gizmo' }, moods: VINTIK },
  { id: 'shpuntik', name: { ru: 'Шпунтик', en: 'Sprocket' }, moods: SHPUNTIK },
  { id: 'iskra', name: { ru: 'Искра', en: 'Spark' }, moods: ISKRA },
  { id: 'luna', name: { ru: 'Луна', en: 'Luna' }, moods: LUNA },
  { id: 'gaika', name: { ru: 'Гайка', en: 'Nutty' }, moods: GAIKA },
  { id: 'pixel', name: { ru: 'Пиксель', en: 'Pixel' }, moods: PIXEL },
  { id: 'robi', name: { ru: 'Роби', en: 'Robi' }, moods: ROBI },
  { id: 'kubik', name: { ru: 'Кубик', en: 'Cubie' }, moods: KUBIK },
  { id: 'tesla', name: { ru: 'Тесла', en: 'Tesla' }, moods: TESLA },
  { id: 'mayak', name: { ru: 'Маяк', en: 'Beacon' }, moods: MAYAK },
  { id: 'sensor', name: { ru: 'Сенсор', en: 'Sensor' }, moods: SENSOR },
  { id: 'moh', name: { ru: 'Мох', en: 'Moss' }, moods: MOH },
  { id: 'chip', name: { ru: 'Чип', en: 'Chip' }, moods: CHIP },
  { id: 'ryzhik', name: { ru: 'Рыжик', en: 'Rusty' }, moods: RYZHIK },
  { id: 'limon', name: { ru: 'Лимон', en: 'Lemon' }, moods: LIMON },
  { id: 'grafit', name: { ru: 'Графит', en: 'Graphite' }, moods: GRAFIT },
  { id: 'olivka', name: { ru: 'Оливка', en: 'Olive' }, moods: OLIVKA },
  { id: 'kosmo', name: { ru: 'Космо', en: 'Cosmo' }, moods: KOSMO },
]
